spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aresa7796/springcloud_config
          username: aresa@qq.com
          password: xxxxxx
          basedir: c:/config/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/