server:
  port: 8012
spring:
  application:
    name: user_service
eureka:
  client:
    service-url:
      defaultZone: http://192.168.8.89:8761/eureka/
ribbon:
   ReadTimeout: 60000
   ConnectTimeout: 60000
   OkToRetryOnAllOperations: false
   MaxAutoRetries: 0
   MaxAutoRetriesNextServer: 1
