spring:
  application:
    name: product
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/shop_test
    username: root
    password: pp527796
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 1
    maxActive: 2
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'ZTM' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

mybatis:
  mapper-locations: classpath:dao/mapping/*.xml,classpath:dao/adapter/mapping/*.xml
  type-aliases-package: com.springzzc.product.model.dto
server:
  port: 8013
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/